version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    versioning-strategy: "increase"
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    commit-message:
      prefix: "build(docker)"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]
    labels:
      - "dependencies"
